name: Abstracted Light
favicon: null
layout_spectrum: 0.6207275432534516
typography_spectrum: 0.7875259674619883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.18092921492643654
  lightness: 0.2666865666396916
  saturation: 0.25153007451444864
  rhythmicContrast: 0.08496769960038364
purpose: []
